name: clinica-backend
services:
- name: api
  source_dir: /
  github:
    repo: seu-usuario/seu-repo
    branch: main
  run_command: node src/server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"